server:
  port: 9000

spring:
  banner:
    location: classpath:banner.txt
  application:
    name: price-notifications

client:
  alpha-vantage:
    url: https://www.alphavantage.co
    key: ${ALPHA_VANTAGE_API_KEY}